# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: shop_user
      MONGO_INITDB_ROOT_PASSWORD: shop_password
      MONGO_INITDB_DATABASE: shop


  alten-shop-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      ENV_MONGODB_HOST: mongodb


volumes:
  mongo_data:
